RelatIn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import updateStatus.urls as updateStatusUrl
import profilePage.urls as profilePageUrl
import addFriend.urls as addFriendUrl
import dashboard.urls as dashboardUrl
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/',  include(updateStatusUrl, namespace='updateStatus')),
    url(r'^profile/', include(profilePageUrl, namespace='profilePage')),
    url(r'^add-friend/', include(addFriendUrl, namespace='addFriend')),
    url(r'^dashboard/', include(dashboardUrl, namespace='dashboard')),
    url(r'^$', RedirectView.as_view(url='status/', permanent = True), name='UpdateStatus'),
]

addFriend/urls.py
from django.conf.urls import url
from .views import index
from .views import add_new_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_new_friend/$', add_new_friend, name='add_new_friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name= 'index'),
    
]

profilePage/urls.py
from django.conf.urls import url
from .views import index
urlpatterns = [
    url(r'^$', index, name = 'index'),
]

updateStatus/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

addFriend/models.py
from django.db import models
from django.core.validators import URLValidator

class FriendList(models.Model):
	name = models.CharField(max_length=30)
	url = models.URLField()
	date = models.DateTimeField(auto_now_add=True)

dashboard/models.py
from django.db import models
from addFriend.models import FriendList
from updateStatus.models import Status
from profilePage.models import Profile
# Create your models here.

class Theme(models.Model):
    name = models.CharField(max_length = 100)

profilePage/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
   name = models.CharField(max_length= 30)
   birthday = models.TextField()
   gender = models.TextField()
   expertise = models.TextField()
   description = models.TextField()
   email = models.TextField()

updateStatus/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    date = models.DateTimeField(auto_now_add = True)
    activity = models.TextField(max_length = 140)

addFriend/forms.py
from django import forms

class Add_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan url',
    }
    name_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan judul...'
    }
    url_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan url...'
    }

    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='Url',required=True, widget=forms.URLInput(attrs=url_attrs))

updateStatus/forms.py
from django import forms

class Status_Form(forms.Form):
    activity_attrs = {
        'type': 'text',
        'class': 'todo-form-textarea',
        'placeholder':'What happened today?'
    }

    activity = forms.CharField(label='', required= True, widget=forms.Textarea(attrs=activity_attrs))

addFriend/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import FriendList  
from .forms import Add_Form


response = {}
def index(request):
    response['title'] = 'Add Friend'
    html = 'addFriend.html'
    response['add_form'] = Add_Form
    response['friend'] = FriendList.objects.all()
    return render(request, html, response)

def add_new_friend(request):
    form = Add_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = FriendList(name=response['name'],url=response['url'])
        friend.save()
        return HttpResponseRedirect('/add-friend/')      

dashboard/views.py
from django.shortcuts import render
from .models import FriendList, Status, Profile
# how to get last data inserted

# Create your views here.
response = {}

expert = ['Writing', 'Skimming', 'Drawing']
def index(request):
    try:
        profile = Profile.objects.get(pk = 1)
        response["profile"] = profile


    except:
        profile = Profile(name="Fran Na Jaya",
                          birthday="25 April",
                          gender="Male",
                          expertise=expert,
                          description="Lion Ha-O~h! Lion Ha-O~h!",
                          email="fullbottles@gmail.com")
        profile.save()

        response["profile"] = profile
    myStatusDataResp = Status.objects.all().count()
    myFriendDataResp = FriendList.objects.all().count()
    response['title'] = 'Dashboard'
    response['friend'] = myFriendDataResp
    response['feed'] = myStatusDataResp
    response['lastFeed'] = Status.objects.all().last()
    html = 'dashboard.html'
    return render(request, html, response)

profilePage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Profile
# Create your views here.

response = {}
expert = ["Writing Skimming Drawing"]
def index(request):

    try:
        profile = Profile.objects.get(pk = 1)
        response["Profile"] = profile
        

    except:
        profile = Profile(name="Fran Na Jaya",
                          birthday="25 April",
                          gender="Male",
                          expertise=expert,
                          description="Lion Ha-O~h! Lion Ha-O~h!",
                          email="fullbottles@gmail.com")
        profile.save()

        response["Profile"] = profile
        response["expertise"] = expert
        
    html = 'profilePage.html'    
    return render(request, html, response)

updateStatus/views.py
from django.shortcuts import render
from .models import Status
from django.http import HttpResponseRedirect
from .forms import Status_Form
from profilePage.models import Profile
# Create your views here.

response = {}
expert = ['Writing', 'Skimming', 'Drawing']
def index(request):
    try:
        profile = Profile.objects.get(pk = 1)
        response["Profile"] = profile
    except:
        profile = Profile(name="Fran Na Jaya",
                          birthday="25 April",
                          gender="Male",
                          expertise=expert,
                          description="Lion Ha-O~h! Lion Ha-O~h!",
                          email="fullbottles@gmail.com")
        profile.save()
        response["Profile"] = profile
    response['name'] = response['Profile'].name
    response['title'] = 'Update Status'
    status = Status.objects.all()
    response['status'] = status
    html = 'updateStatus.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['activity'] = request.POST['activity']
        status = Status(activity = response['activity'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

addFriend/templates/addFriend.html
{% extends "layout/base.html" %}

{% block content %}
<div class = "normalize">
        
    <div class = "row_title" style="text-align: left">Add Friend</div>
    <h1></h1>
    <section name="input-status" id="input-status">
        <div class="container">
            <form class="title-and-add" method="POST" action="add_new_friend/">
                {% csrf_token %}
                <table>
                    <tr>
                        <td style="font-family: 'Muli'">
                            Name
                        </td>
                        <td>
                            <input type="text" name="name" id="" required="required" style="width: 910px;"/>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-family: 'Muli'">
                            URL
                        </td>
                        <td>
                            <input type="url" name="url" id="" required="required" style="width: 910px;" />
                        </td>
                    </tr>
                </table>
                <button type="submit" class="button btn-success" style="font-family: 'Muli'; float:right;" >Add Friend</button>
            </form>
        </div>
    </section>
    <section name="my-list" id="my-list">
        <div class="container">
            <h2 class="row_title">Friend List</h2>
            <div class="centre-and-add">
            <div class="flexfriend">
                {% if friend %}
                    {% for data in friend %}
                        <div class="flex-itemf">
                            {{data.name}}
                            <br>
                            {{data.date}}
                            <br>
                            <a href ="{{data.url}}">{{data.url}}</a>
                        </div>
                    {% endfor %}
                {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada teman :(.
                </div>
                {% endif %}
            </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}

dashboard/templates/dashboard.html
{% extends "layout/base.html" %}

{% block content %}
<div class = "normalize">

    <div class = "card">
        <div class = "card_item">
            <div class = "col_1">
                STATISTIC
            </div>
            <div class = "row_title">
                <img src = "https://kumparan.com/default-user.png"/>
                {{profile.name}}
            </div>
            <div class = "row_1">
                <div class = "friend">
                    <div><b>Friend</b> : {{friend}} person</div>
                </div>
                <div class = "statistic">
                    <b>Feeds</b> : {{feed}} feed
                </div>
            </div>
            <div class = "row_1">
                <b>LastFeed :</b>
            </div>
            <div class = "flex">
            {%if lastFeed %}
                <div class = "flex-item">
                    <img src = "https://kumparan.com/default-user.png"/>
                    fran na jaya
                    <br>{{lastFeed.activity}}
                    <br>{{lastFeed.date}}
                </div>
            </div>
            {% else %}
            <div class="alert alert-danger text-center" style="font-family:'Muli'">
                You haven't posted anything :(
            </div>
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

dashboard/templates/layout/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset ='UTF-8'>
        <meta name = "viewport" content = "width=device-width, initial-scale =1.0">
        <meta http-equiv="X-UA Compatible" content ="ie=edge">
        <!-- Semua masukkin ya header footer css nya kayak gini -->
        <link rel="stylesheet" type="text/css" href = "{% static 'css/headerfooter.css' %}" />
        <!-- ini baru css sendiri2-->
        <link rel="stylesheet" type="text/css" href = "{% static 'css/dashBoard.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Muli|Ubuntu" rel="stylesheet"/>

        <link rel ="stylesheet" type = "text/css" href = "{% static 'css/profilePage.css' %}"/>
        <link rel ="stylesheet" href ="https://www.w3schools.com/w3css/4/w3.css">

        <title>
            {{title}}
        </title>
    </head>

    <body>
            <header>
                {% include "partials/header.html" %}
            </header>

            <content>
                {% block content %}
                <!--code goes here-->
                {% endblock %}
            </content>

            <footer>
                {% include "partials/footer.html" %}
            </footer>
    </body>
</html>

dashboard/templates/partials/footer.html
<div class = "footer-basic">
    <p>&copy; copyright 2017</p>
</div>

profilePage/templates/profilePage.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<div class = "normalize">
	
	<h4 style="text-align: left;">Profile</h4>
	<div style="text-align: center;"><img class="img-circle" src="https://kumparan.com/default-user.png"/></div>
	<hr />
		<section>
			<h2 style="text-align: center;">{{Profile.name}}</h2>
		</section>
	<hr />
	<section style="margin: auto;">
		<table style="width: 547px; height: 122px; text-align: left;" align="center">
			<tbody>
				<tr>
					<td style ="width: 169.2px">Birthday</td>
					<td style ="width: 356.8px">{{Profile.birthday}}</td>
				</tr>
				<tr>
					<td style ="width: 169.2px">Gender</td>
					<td style ="width: 356.8px">{{Profile.gender}}</td>
				</tr>
				<tr>
					<td style ="width: 169.2px">Expertise</td>
					{% for text in expertise %}
					<td>{{text}}</td>
					{% endfor %}
				</tr>
				</td>
				</p>
				<tr>
					<td style ="width: 169.2px">Description</td>
					<td style ="width: 356.8px">{{Profile.description}}</td>
				</tr>
				<tr>
					<td style ="width: 169.2px">Email</td>
					<td style ="width: 356.8px">{{Profile.email}}</td>
				</tr>
			</tbody>
		</table>
	</section>
	<section>

	</section>
	<hr />

</div>
{% endblock %}

updateStatus/templates/updateStatus.html
{% extends "layout/base.html" %}

{% block content %}
<div class = "normalize">

    <h1></h1>
    <section name="input-status" id="input-status">
        <div class="container">
            <form id="box" method="POST" action="{% url 'updateStatus:add_status' %}">
                {% csrf_token %}
                {{ status_form }}
                <br>
                <input style="float: right; font-family:'Muli'" type="submit" value="POST">
            </form>
        </div>
    </section>
    <section name="show-status">
        <div class="container" id="box">
            <h2 style="border-bottom:7px solid #33C980; padding-bottom:7px; font-family:'Muli'">My Status</h2>
            <div class="flex" id="box" style="margin-top:0px">
                {%if status %}
                    {% for data in status %}
                        <div class="flex-item" id="box-item" style="font-family:'Muli'">
                                <img src = "https://kumparan.com/default-user.png"/  style="margin-right:20px;width:70px; height: 70px; border-radius:100%; float:left">
                            <div style="font-size:20px; font-weight:bold; margin-bottom: 10px;">
                                {{ Profile.name }}
                            </div>
                            <div style="font-size: 18px">
                                {{data.activity}} 
                            </div>
                            <div style="font-size:12px">
                                {{data.date}}
                            </div>                         
                            <h2 style="border-bottom:4px solid #33C980; padding-bottom:5px"></h2> 
                        </div>
                    {% endfor %}
                {% else %}
                <div class="alert alert-danger text-center" style="font-family:'Muli'">
                    You haven't posted anything :(
                </div>
                {% endif %}
            </div>
        </div>
    </section>

</div>
{% endblock %}